---

- name: Show Commands Playbook
  hosts: 172.18.173.64
  connection: network_cli
  gather_facts: no
  connection: local
  ignore_errors: yes
  become: yes
  become_method: enable
  strategy: linear

  tasks:
  - name: Test reachability to 172.18.173.64 using default vrf
    ios_ping:
      dest: 172.18.173.64
...
