---

- name: Show Commands Playbook
  hosts: 172.18.173.64
  gather_facts: no
  connection: local
  ignore_errors: yes
  become: yes



  tasks:

  - name: Change ssh port to 22
    set_fact:
      ansible_port: 22
  - name: Test reachability to 172.18.173.64 using default vrf
    ios_ping:
      dest: 172.18.173.64
      timeout: 3000
...
